# Generated by Django 3.2.6 on 2021-08-15 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lost_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('desciption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('contact', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LostFound.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Found_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('desciption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('contact', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LostFound.userregistration')),
            ],
        ),
    ]
