# Generated by Django 3.2.6 on 2021-08-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostFound', '0002_alter_found_item_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found_item',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='lost_item',
            name='desciption',
        ),
        migrations.AddField(
            model_name='lost_item',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
